[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/for-loops/*"
  to = "/for-loops/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
